from PyQt5 import QtCore, QtGui, QtWidgets # type: ignore
import os 
import yaml #type:ignore

# Cargar la configuración desde el archivo YAML
with open('config.yaml', 'r') as f:
    config = yaml.safe_load(f)

# Cargar la configuración desde el archivo YAML
base_path = os.path.abspath(os.path.join(os.path.dirname(__file__), config['base_path']))

# Ahora, unir con los paths del YAML
imagenes_front_path = os.path.join(base_path, config['imagenes_path'])
#variables imagenes
image_PDF = os.path.join(imagenes_front_path, 'pdf.png')
image_Excel = os.path.join(imagenes_front_path, 'excel.png')
image_selec = os.path.join(imagenes_front_path, 'seleccion.png')
image_fechaDer = os.path.join(imagenes_front_path, 'flecha-correcta.png')
image_flechaIzq = os.path.join(imagenes_front_path, 'flecha.png')
image_verificado = os.path.join(imagenes_front_path,"verificado.png")
image_next = os.path.join(imagenes_front_path, "Next.png") 

        


class Ui_frmPrincipal(object):
    def setupUi(self, frmPrincipal):
        frmPrincipal.setObjectName("Extractor_De_Tablas")
        frmPrincipal.setEnabled(True)
        frmPrincipal.setFixedSize(636, 582)
        frmPrincipal.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        frmPrincipal.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        frmPrincipal.setAcceptDrops(False)
        frmPrincipal.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(frmPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_Import_PDF = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Import_PDF.setGeometry(QtCore.QRect(50, 110, 80, 35))
        self.btn_Import_PDF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(image_PDF), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Import_PDF.setIcon(icon)
        self.btn_Import_PDF.setIconSize(QtCore.QSize(20, 20))
        self.btn_Import_PDF.setFlat(False)
        self.btn_Import_PDF.setObjectName("btn_Import_PDF")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 66, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_SavePages = QtWidgets.QPushButton(self.centralwidget)
        self.btn_SavePages.setGeometry(QtCore.QRect(190, 340, 61, 41))
        self.btn_SavePages.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_SavePages.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(image_selec), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_SavePages.setIcon(icon1)
        self.btn_SavePages.setIconSize(QtCore.QSize(30, 30))
        self.btn_SavePages.setFlat(True)
        self.btn_SavePages.setObjectName("btn_SavePages")
        self.Regions_View = QtWidgets.QGraphicsView(self.centralwidget)
        self.Regions_View.setGeometry(QtCore.QRect(285, 20, 329, 470))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Regions_View.sizePolicy().hasHeightForWidth())
        self.Regions_View.setSizePolicy(sizePolicy)
        self.Regions_View.setObjectName("Regions_View")
        self.btnCreateExcel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCreateExcel.setGeometry(QtCore.QRect(193, 430, 41, 41))
        self.btnCreateExcel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCreateExcel.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(image_Excel), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCreateExcel.setIcon(icon2)
        self.btnCreateExcel.setIconSize(QtCore.QSize(30, 30))
        self.btnCreateExcel.setFlat(True)
        self.btnCreateExcel.setObjectName("btnCreateExcel")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(50, 440, 121, 21))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 406, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btn_der = QtWidgets.QPushButton(self.centralwidget)
        self.btn_der.setGeometry(QtCore.QRect(511, 510, 31, 31))
        self.btn_der.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_der.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(image_fechaDer), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_der.setIcon(icon3)
        self.btn_der.setFlat(True)
        self.btn_der.setObjectName("btn_der")
        self.btn_Izq = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Izq.setGeometry(QtCore.QRect(351, 510, 31, 31))
        self.btn_Izq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Izq.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(image_flechaIzq), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Izq.setIcon(icon4)
        self.btn_Izq.setFlat(True)
        self.btn_Izq.setObjectName("btn_Izq")
        self.label_Verificado = QtWidgets.QLabel(self.centralwidget)
        self.label_Verificado.setGeometry(QtCore.QRect(40, 172, 31, 21))
        self.label_Verificado.setText("")
        self.label_Verificado.setPixmap(QtGui.QPixmap(image_verificado))
        self.label_Verificado.setScaledContents(True)
        self.label_Verificado.setObjectName("label_Verificado")
        self.label_oculto = QtWidgets.QLabel(self.centralwidget)
        self.label_oculto.setGeometry(QtCore.QRect(80, 170, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_oculto.setFont(font)
        self.label_oculto.setObjectName("label_oculto")
        self.label_pageStart = QtWidgets.QLabel(self.centralwidget)
        self.label_pageStart.setGeometry(QtCore.QRect(423, 510, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_pageStart.setFont(font)
        self.label_pageStart.setObjectName("label_pageStart")
        self.label_Diagonal = QtWidgets.QLabel(self.centralwidget)
        self.label_Diagonal.setGeometry(QtCore.QRect(444, 516, 20, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Diagonal.setFont(font)
        self.label_Diagonal.setObjectName("label_Diagonal")
        self.label_pageEnd = QtWidgets.QLabel(self.centralwidget)
        self.label_pageEnd.setGeometry(QtCore.QRect(462, 510, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_pageEnd.setFont(font)
        self.label_pageEnd.setObjectName("label_pageEnd")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(128, 277, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 250, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 347, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 299, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(174, 300, 47, 13))
        self.label_8.setObjectName("label_8")
        self.CB_PageStart = QtWidgets.QComboBox(self.centralwidget)
        self.CB_PageStart.setGeometry(QtCore.QRect(50, 277, 51, 20))
        self.CB_PageStart.setObjectName("CB_PageStart")
        self.CB_PageEnd = QtWidgets.QComboBox(self.centralwidget)
        self.CB_PageEnd.setGeometry(QtCore.QRect(160, 277, 51, 20))
        self.CB_PageEnd.setObjectName("CB_PageEnd")
        self.btn_Next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Next.setGeometry(QtCore.QRect(61, 495, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Next.setFont(font)
        self.btn_Next.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Next.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(image_next), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Next.setIcon(icon5)
        self.btn_Next.setIconSize(QtCore.QSize(50, 50))
        self.btn_Next.setFlat(True)
        self.btn_Next.setObjectName("btn_Next")
        self.btn_Import_Excel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Import_Excel.setGeometry(QtCore.QRect(139, 110, 80, 35))
        self.btn_Import_Excel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Import_Excel.setIcon(icon2)
        self.btn_Import_Excel.setIconSize(QtCore.QSize(20, 20))
        self.btn_Import_Excel.setFlat(False)
        self.btn_Import_Excel.setObjectName("btn_Import_Excel")
        frmPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(frmPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 21))
        self.menubar.setObjectName("menubar")
        frmPrincipal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frmPrincipal)
        self.statusbar.setObjectName("statusbar")
        frmPrincipal.setStatusBar(self.statusbar)

        self.retranslateUi(frmPrincipal)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmPrincipal)

        #desabilitar y ocultar
        self.label_Verificado.setVisible(False)
        self.label_oculto.setVisible(False)
        # mostrar labels
        self.label_pageEnd.setVisible(False)
        self.label_Diagonal.setVisible(False)
        self.label_pageStart.setVisible(False)
        # activar botones
        self.CB_PageStart.setEnabled(False)
        self.CB_PageEnd.setEnabled(False)
    

        self.btn_der.setEnabled(False)
        self.btn_Izq.setEnabled(False)
        self.btn_SavePages.setEnabled(False)

        #mostrar btn create_excel
        self.comboBox.setEnabled(False)
        self.btnCreateExcel.setEnabled(False)
        self.btn_Next.setEnabled(False)





    def retranslateUi(self, Extractor_De_Tablas):
        _translate = QtCore.QCoreApplication.translate
        Extractor_De_Tablas.setWindowTitle(_translate("Extractor_De_Tablas", "Extraer Tablas"))
        self.btn_Import_PDF.setText(_translate("Extractor_De_Tablas", "PDF"))
        self.label.setText(_translate("Extractor_De_Tablas", "1. Importa tu archivo"))
        self.comboBox.setItemText(0, _translate("Extractor_De_Tablas", "Una Hoja"))
        self.comboBox.setItemText(1, _translate("Extractor_De_Tablas", "Multiples Hojas"))
        self.label_3.setText(_translate("Extractor_De_Tablas", "4. Selecciona una Opción"))
        self.label_oculto.setText(_translate("Extractor_De_Tablas", "Archivo Seleccionado"))
        self.label_pageStart.setText(_translate("Extractor_De_Tablas", "0"))
        self.label_Diagonal.setText(_translate("Extractor_De_Tablas", "/"))
        self.label_pageEnd.setText(_translate("Extractor_De_Tablas", "0"))
        self.label_4.setText(_translate("Extractor_De_Tablas", "A"))
        self.label_5.setText(_translate("Extractor_De_Tablas", "2. Ingresar el rango de paginas:"))
        self.label_6.setText(_translate("Extractor_De_Tablas", "3. Seleccionar Datos"))
        self.label_7.setText(_translate("Extractor_De_Tablas", "Inicial"))
        self.label_8.setText(_translate("Extractor_De_Tablas", "Final"))
        self.btn_Next.setText(_translate("Extractor_De_Tablas", "Siguiente"))
        self.btn_Import_Excel.setText(_translate("Extractor_De_Tablas", "Excel"))

    def disable_minimize_button(self, frmPrincipal):
        window_flags = frmPrincipal.windowFlags()
        window_flags &= ~QtCore.Qt.WindowMinimizeButtonHint
        frmPrincipal.setWindowFlags(window_flags)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmPrincipal = QtWidgets.QMainWindow()
    ui = frmPrincipal()
    ui.setupUi(frmPrincipal)
    frmPrincipal.show()
    sys.exit(app.exec_())

       